apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql
  template:
    metadata:
      labels:
        service: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.image.repo }}/rs-mysql-db:{{ .Values.image.version }}   
        imagePullPolicy: {{ .Values.image.pullPolicy }}                       
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 700Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    service: mysql
spec:
  selector:
    service: mysql
  ports:
  - name: http
    port: 3306
    targetPort: 3306
